### ISSUE TITLE
Associate with *.java files

### ISSUE THREAD

**Issue by akurtakov** [flathub/org.eclipse.Java#1]
It's worth considering whether other file associations will be helpful too.

**Comment by akurtakov** [comment]
After looking at editors available *.gradle and pom.xml would be nice.

**Comment by zztestxx** [comment]
Will this support c++ with working breakpoints in the debugger on Fedora 31??? Installing eclipse on F31 straight from eclipse.org does not have working breakpoints in the debugger.

**Comment by mbooth101** [comment]
Fixed in 88942a8
