### ISSUE TITLE
Associating URI scheme handlers with Flatpak app seems non-functional

### ISSUE THREAD

**Issue by mickaelistria** [flathub/org.eclipse.Java#10]
With a regular (non-flatpak) Eclipse IDE installation on Fedora 31
* Window > Preferences > General > Link Handlers; check `eclipse+mpc` so it marks in the OS it's handled by the Eclipse IDE
* Open an html page containing a eclipse+mpc link in Firefox. Here is an example of such page
```html
<html>
<body>
<a href="eclipse+mpc://marketplace.eclipse.org/install/1640500">install</a>
</body>
</html>
```
* Click the link
=> Firefox suggests to handle link with Eclipse IDE, and clicking it opens the MPC dialog

Repeat the same steps with a Flatpak of Eclipse SDK
=> Firefox says URL cannot be handled.

It seems to me the reason is that the xdg stuff that's configured under the hood isn't properly configured in case of flatpak. According to Eclipse's Link Handlers preference page, it sets the value to `/apps/eclipse` while it should probably be `flatpak run org.eclipse.<variation>`.

**Comment by TingPing** [comment]
It just isn't listed in the desktop file: https://github.com/flathub/org.eclipse.Java/blob/master/org.eclipse.Java.desktop#L9

Compare it to the desktop file the package provided.

**Comment by khatchad** [comment]
Seems related to https://github.com/flathub/org.gnome.Evolution/issues/104.
