### ISSUE TITLE
(PDE) Launch configuration doesn't propertly expand basedir for ${workspace_loc:someProject}

### ISSUE THREAD

**Issue by mickaelistria** [flathub/org.eclipse.Java#11]
I'm trying to run some m2e tests that require a proper basedir to succeed. In the PDE Launch Configuration "Arguments" tab, the running directory is set to `Default: ${workspace_loc:org.eclipse.m2e.tests}`, good.
If I run it from a Flatpak IDE, I see the test failing. When debugging, it appears that the running directory (`new File(".").getAbsolutePath()`) is not set to the desired path but to my user home directory.
I stop the IDE and use another local installation from a zip package, and start the exact same launch configurion with the exact same settings => test succeed and running directory seems correct.

This identifies that variable substitution here seems faulty. I don't know if it's general to all launch configs, to the whole IDE, or just specific to the PDE Launch.

**Comment by vrubezhny** [comment]
In my case, when I run a JUnit test from a Flatpak IDE,  `new File(".").getAbsolutePath()` returns a value like `/home/user/projects/linuxtools/runtime-New_configuration/org.test.maven.proj1/` - which looks like a correct value (default workspace path + path to project). 

Any suggestions on how can I reproduce it?

**Comment by mickaelistria** [comment]
Sorry, it's been a while since I tried it and don't have more details than what I wrote in the report. So if you tried that and could see it working, it may be already fixed.
