### ISSUE TITLE
Document what is the recommended way to add changes to eclipse.ini

### ISSUE THREAD

**Issue by mauromol** [flathub/org.eclipse.Java#14]
I recently installed Eclipse 2020-06 through flatpak, because the standard package can't run properly on my Linux Mint 18.3 (based on Ubuntu 16.04), due to old GTK3 libraries. This version works great instead, thank you very much for your effort!

My first question: what is the recommended way to proceed when a change to eclipse.ini is required?

By now I changed /var/lib/flatpak/app/org.eclipse.Java/current/active/files/eclipse/eclipse.ini and it seems to work (a first attempt I made was failing, but I think it was just me putting the necessary option in the wrong position), but knowing about how flatpak packages should work I'm not sure it's the right thing to do.

Actual use case: adding JVM args (to set system properties or to change the default Xmx value of 2 GB, etc.).

**Comment by mbooth101** [comment]
Well, ```/var/lib/flatpak/app/org.eclipse.Java/current/active``` is a symlink to the current active revision of the application. So when you update, the target of the symlink will change and your changes will be "undone" (not really undone, but you are using a new version of the app without your changes). This isn't unique to flatpak, you can expect similar behaviour in other read-only situations too, like in RPM-based installations, etc.

The two usual ways to customise Eclipse start up are as follows:

1. Make a custom eclipse.ini somewhere and tell Eclipse to use that instead by passing ```--launcher.ini <file>``` for example:

```
$ flatpak run org.eclipse.Java --launcher.ini /home/mbooth/my/custom/eclipse.ini
```

2. Just pass the additional options directly to the Eclipse executable as normal, for example:

```
$ flatpak run org.eclipse.Java -vmargs -Xmx4g -Dmy.sysprop=some_value
```

BTW the Eclipse launcher and runtime options are documented at https://help.eclipse.org and also in Eclipse's built-in help system so I won't be duplicating that information here.

I hope this helps!

**Comment by mauromol** [comment]
Hi Mat, thanks for this information! I think replacing eclipse.ini entirely is too risky on upgrade, because from one version to the other it may contain other things that are needed. Passing additional options directly to Eclipse command line I think is the best solution, at least for the cases I have in mind. Will in this case -vmargs specified on command line be merged with those provided by eclipse.ini or will they replace each other?

IMHO it would be very useful to document this kind of tips, at least here (probably in the wiki?), perhaps in the form of FAQs, what do you think?

**Comment by akurtakov** [comment]
A README.md file with link to the respective document explaining it is worth it. 
Mauro, I believe you can make it too and probably better than Mat as you can can put an explanation like "in order to do XXX ..." and after spending time on given issue we just start lacking to explain the solution with simple words :) . PR would be welcome.

**Comment by mbooth101** [comment]
> Will in this case -vmargs specified on command line be merged with those provided by eclipse.ini or will they replace each other?

In case you didn't try it and see for yourself, the arguments are appended to those in the eclipse.ini file.

In the case where an argument is given twice (i.e. once in eclipse.ini and once on command line) then the command line option wins. (If I recall OpenJDK's behaviour correctly when giving an option multiple times the last one wins. For example, I believe invoking ```java -Xmx2g -Xmx4g``` should result in 4 gigabyte heap size.)

**Comment by ugale-deepak3010** [comment]
Any update guys. I am struggling in Fedora41.
