### ISSUE TITLE
"AutoRegisterSchemeHandlersJob"

### ISSUE THREAD

**Issue by ghost** [flathub/org.eclipse.Java#26]
Just installed the flatpak and an error showed up. Using Fedora 33.
Hope the screenshot helps.
![flatpakdevshimerror](https://user-images.githubusercontent.com/63687979/103690430-79e7cd80-4f73-11eb-955c-b846b33c1399.png)

**Comment by rstdigo** [comment]
Nevermind, I'm using eclipse from the official repo.

**Comment by akurtakov** [comment]
It's an issue we are working on.

**Comment by akurtakov** [comment]
Should be fixed now.
