### ISSUE TITLE
Right-click > Open With > Other... > System Editors doesn't list applications from host

### ISSUE THREAD

**Issue by mickaelistria** [flathub/org.eclipse.Java#3]
I'm trying to open a `.jpg` file from Eclipse IDE into Gimp.
I try "right-click > Open With > Other... > System Editors" but cannot see my host applications in here, only some applications from sandbox (like gtk3-demo).
However, if I do "right-click > Open With > System Editor", then I see a dialog asking me to chose for a System Editor, and this one shows Gimp and other relevant applications that are not in the sandbox.

**Comment by akurtakov** [comment]
I've just tried with EoG and Open With there is empty too. Seems like some kind of portal will have to be added to properly handle the g_app_info* calls.

**Comment by akurtakov** [comment]
@alexlarsson Alex, what do you think? Is it feasible? IMHO if we are ever to see nautilus (or any file browser) being usable when shipped as flatpak being able to list mime handlers and opening with one of them would be a must.

**Comment by TingPing** [comment]
This is a subject for https://github.com/flatpak/xdg-desktop-portal

There are some discussions on like a share portal and have been discussions on being able to just directly launch other applications.

**Comment by akurtakov** [comment]
@TingPing  Can you link us to the appropriate xdg-desktop-portal issue?

**Comment by TingPing** [comment]
I guess this one is the most relevant: https://github.com/flatpak/xdg-desktop-portal/issues/12

**Comment by Mailaender** [comment]
Can't reproduce. I get open with for host applications:

![image](https://github.com/flathub/org.eclipse.Java/assets/756669/30db8b6c-2215-4660-aa06-40236a0dd8fe)
