### ISSUE TITLE
[CDT] Restarting Eclipse after CDT installation causes an error

### ISSUE THREAD

**Issue by mcoufal** [flathub/org.eclipse.Java#37]
When I try to install CDT using 'Install New Software...' wizard, I get an error after trying to restart Eclipse (see screenshot).

How To Reproduce:
1. open 'Install New Software...' wizard
2. use update site: https://download.eclipse.org/tools/cdt/builds/10.3/cdt-10.3.0-rc1/
3. select and install 'CDT Main Features' group
4. click on 'Restart Now' when prompted

At this point I can see the error, but Eclipse starts fine when started again. The workspace log is empty.

My Configuration:
Eclipse SDK
Version: 2021-06 (4.20)
Build id: I20210601-0600
Java runtime version: 15.0.2+7-27
Java version: 15.0.2
Installed: 
Eclipse C/C++ Development Tools	10.3.0.202105311920

![cdt_error_after_install](https://user-images.githubusercontent.com/26609411/120490771-f8c52300-c3b8-11eb-843a-5a0a132f7a20.png)
.

**Comment by Mailaender** [comment]
Restarting does not work in general.

**Comment by Mailaender** [comment]
Retested and restarting now seems to work just fine.
