### ISSUE TITLE
Unable to open project in system explorer

### ISSUE THREAD

**Issue by Mek101** [flathub/org.eclipse.Java#39]
![Schermata da 2021-06-17 12-39-18](https://user-images.githubusercontent.com/34246799/122381397-2ab5b800-cf69-11eb-91d5-7b74ead3d5c1.png)

Looks like eclipse is unable to communicate with a session bus

Setup:
Manjaro Gnome
Flatpak 1.11.1
org.eclipse.Java 4.19

**Comment by vrubezhny** [comment]
@Mek101 could you please verify if the latest build fixes the issue?

I cannot reproduce the issue using Flatpak 1.10.2, org.eclipse.Java 2021-06 (4.20.0) on Fedora (Gnome 3.38.5, Wayland) - `Show-in -> System Explorer` works fine for me.

**Comment by Mek101** [comment]
I still have this issue on 2021-06.
org.eclipse.Java 4.20

**Comment by akurtakov** [comment]
Just verified on 4.23 and it works for me too.
