### ISSUE TITLE
Support for KDE Global Menu.

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [flathub/org.eclipse.Java#41]
It would be great if you add support for KDE's global menu, taking in mind the main Eclipse version supports it.

This is what I am getting using the flatpak version:

![Screenshot_20210701_124745](https://user-images.githubusercontent.com/80849765/124168300-91a79680-da6a-11eb-807c-364895e42b73.png)

This is what I get using the main version:

![Screenshot_20210701_125555](https://user-images.githubusercontent.com/80849765/124169346-c49e5a00-da6b-11eb-83d7-a8c066966edd.png)

**Comment by mbooth101** [comment]
Thanks for the report.

I suppose this is because Eclipse Flatpak uses the Gnome runtime, and not the KDE runtime. I'm not at all familiar with KDE so this will take some investigation.

**Comment by akurtakov** [comment]
Eclipse can't use KDE global menu when downloaded from upstream. Thus fix should be there. Please consider opening bug at https://bugs.eclipse.org/bugs/ but you may need to help with adding support for it.
