### ISSUE TITLE
Update to Eclipse 4.24

### ISSUE THREAD

**Issue by ERF4** [flathub/org.eclipse.Java#63]
They released a new version on June 14. [should be here](https://download.eclipse.org/technology/epp/downloads/release/2022-06/R/)

Updating the file with the new version looks pretty simple, but I'm not gonna do it myself because I'm new and I have no idea how this stuff works. Also why would anyone trust me. 

Is there really no way to just automate this? One of the main things that drew me to flatpak was always having up-to-date software. But it seems kind of inefficient to need maintainers to constantly watch for updates and just change a link every few months. Idk, just an outsider's two cents.

**Comment by akurtakov** [comment]
In the future feel free to propose a PR. I try to put it with smallest delay but my upstream Eclipse duties sometimes prevail. I'll update today.
