### ISSUE TITLE
Eclipse freeze and crash every first startup after booting

### ISSUE THREAD

**Issue by henryju** [flathub/org.eclipse.Java#68]
Hi,

I started to use Eclipse as flatpak few days ago. I noticed that every time I boot my computer, the first time I launch Eclipse, the UI will freeze after displaying the workspace. After a while (~1 min?), the app will crash without any error message.
Then if I try to restart Eclipse, it will successfully start and I can use it.

How can I investigate that problem? Is there any crash dump available somewhere when a flatpak dies?

I'm on Fedora 36, KDE spin, X11.
Flatpak 1.12.7
org.eclipse.Java 4.24

**Comment by akurtakov** [comment]
I've just pushed 4.26 release . Would you please test with it ?

**Comment by henryju** [comment]
Unfortunately, I had to switch to Ubuntu, so I am not using flatpak anymore. Feel free to close this issue.

**Comment by akurtakov** [comment]
You can use the flatpak on ubuntu too but I understand how slow reaction here forced you to move to other solution.

**Comment by henryju** [comment]
Just to be clear, I didn't move because of this issue :) Thanks for the follow-up.
