### ISSUE TITLE
Flatpak update fail file corrupted

### ISSUE THREAD

**Issue by jgarcia900506** [flathub/org.eclipse.Java#99]
![Captura de pantalla_20240914_004637](https://github.com/user-attachments/assets/a57d162e-844c-47c6-9a03-7fd05f3b5d1d)

So, today the flatpak show me a one update for this package, but... the update fail every time, read the "org.eclipse.Java.json" file, and validate files and file validators, I look that the next two files on repository "https://repo.eclipse.org/content/repositories/linuxtools/org/eclipse/linuxtools/flatpak/flatpak-dev-shim/1.0.1-SNAPSHOT/":

- flatpak-dev-shim-1.0.1-SNAPSHOT.jar
-  flatpak-dev-shim-1.0.1-SNAPSHOT.so

but their sha256 file validators not exists, I guess that it is the trouble.

**Comment by jgarcia900506** [comment]
Or what is the hash that indicate on this error:
Aborted due to failure (** app/org.eclipse.Java/x86_64/stable desde el repositorio remoto flathub: opcode close: Corrupted file object; checksum expected='d721d1086258e6a357dc2490c934a5060e954bdca6b6f8f2b4974bd2c2e96dc4' actual='a5a65867995ab9b635146575e18527123d764d6fb4a9abd607dab1364a6251fe')

**Comment by Mailaender** [comment]
I think it is a @flatpak issue not related to this manifest.
